apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: my-app
type: Opaque
data:
    POSTGRES_USER: cG9zdGdyZXM=
    POSTGRES_PASSWORD: cG9zdGdyZXM=
    POSTGRES_DB: b3RwX3NlcnZpY2U=
    POSTGRES_HOST: ZGI= # not picked up in container
    POSTGRES_PORT: NTQzMg==
    POSTGRES_SSLMODE: ZGlzYWJsZQ==  # not picked up in container  